# Generated by Django 5.0.1 on 2025-11-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Create User model first (managed=False, table already exists in DB)
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('auth', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,  # Table already exists, Django won't create it
            },
        ),
        # Create UserPayment model (managed=True, Django will create this table)
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user')),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
                'db_table': 'user_payments',
                'ordering': ['-payed_at'],
                'managed': True,
            },
        ),
    ]
