# Generated by Django 5.0.1 on 2025-11-14 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Create User model state (managed=False, but create table if it doesn't exist)
        # We use SeparateDatabaseAndState to create table if needed
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                        ('auth', models.IntegerField(default=0)),
                        ('status', models.IntegerField(default=0)),
                        ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                        ('active_until', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'users',
                        'managed': False,  # Django won't manage this table after creation
                    },
                ),
            ],
            database_operations=[
                # Create users table if it doesn't exist (safe for existing tables)
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS users (
                            id BIGINT NOT NULL PRIMARY KEY,
                            auth INTEGER DEFAULT 0,
                            status INTEGER DEFAULT 0,
                            full_name VARCHAR(200),
                            active_until TIMESTAMPTZ
                        );
                    """,
                    reverse_sql="-- Cannot reverse table creation for managed=False model",
                ),
            ],
        ),
        # Create UserPayment model (managed=True, Django will create this table)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserPayment',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('payed_at', models.DateTimeField(auto_now_add=True)),
                        ('deadline', models.DateField()),
                        ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.user')),
                    ],
                    options={
                        'verbose_name': 'User Payment',
                        'verbose_name_plural': 'User Payments',
                        'db_table': 'user_payments',
                        'ordering': ['-payed_at'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                # Create user_payments table manually (without foreign key first)
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS user_payments (
                            id SERIAL PRIMARY KEY,
                            payed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                            deadline DATE NOT NULL,
                            sum NUMERIC(10, 2) NOT NULL,
                            user_id BIGINT NOT NULL
                        );
                        CREATE INDEX IF NOT EXISTS user_payments_user_id_idx ON user_payments(user_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS user_payments;",
                ),
                # Add foreign key constraint if users table exists
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
                                IF NOT EXISTS (
                                    SELECT 1 FROM information_schema.table_constraints 
                                    WHERE constraint_name = 'user_payments_user_id_fkey'
                                ) THEN
                                    ALTER TABLE user_payments 
                                    ADD CONSTRAINT user_payments_user_id_fkey 
                                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
                                END IF;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="ALTER TABLE user_payments DROP CONSTRAINT IF EXISTS user_payments_user_id_fkey;",
                ),
            ],
        ),
    ]
