# Generated by Django 5.0.1 on 2025-11-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DurationOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(help_text='Time value (e.g., 1, 2, 3)')),
                ('time_type', models.CharField(choices=[('sekund', 'Sekund'), ('minut', 'Minut'), ('soat', 'Soat')], default='soat', help_text='Time unit: sekund, minut, or soat', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this option')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duration Option',
                'verbose_name_plural': 'Duration Options',
                'db_table': 'duration_options',
                'ordering': ['display_order', 'time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleInterval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(help_text='Time value (e.g., 5, 10, 30)')),
                ('time_type', models.CharField(choices=[('sekund', 'Sekund'), ('minut', 'Minut'), ('soat', 'Soat')], default='minut', help_text='Time unit: sekund, minut, or soat', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this option')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule Interval',
                'verbose_name_plural': 'Schedule Intervals',
                'db_table': 'schedule_intervals',
                'ordering': ['display_order', 'time'],
                'managed': False,
            },
        ),
    ]
